name: Notify Slack

decsription: Sends Slack notifications.

inputs:
  status:
    description: Whether to notify for a successful, a failed or a cancelled CI. Pass job status for ease, or hexadecimal code otherwise to display weird things (e.g. \#ff00ff).
    required: true
    type: boolean
  webhook:
    description: Slack webhook to send notification.
    required: true
    type: string
  message:
    description: Slack message to display along the notification.
    required: true
    type: string
    default: <https://www.youtube.com/watch?v=dQw4w9WgXcQ|Something happened.>

permissions:
  contents: read

runs:
  using: 'composite'

  steps:
    - name: Send failure Slack notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ inputs.webhook }}
        SLACK_USERNAME: GitHub
        SLACK_ICON_EMOJI: ':polylang:'
        SLACK_COLOR: ${{ inputs.color }}
        SLACK_TITLE: ${{ github.repository }}
        SLACK_MESSAGE: ${{ inputs.message }}
        SLACK_FOOTER: 'Sent with pleasure by WP Syntex.'
