name: Notify Slack

decsription: Sends Slack notifications.

inputs:
  is-success:
    description: Whether to notify for a successful CI or not.
    required: true
    type: boolean
  webhook:
    description: Slack webhook to send notification.
    required: true
    type: string

runs:
  using: 'composite'

  steps:
    - name: Send success Slack notification
      uses: rtCamp/action-slack-notify@v2
      if: ${{ inputs.is-success == true }}
      env:
        SLACK_WEBHOOK: ${{ inputs.webhook }}
        SLACK_USERNAME: GitHub
        SLACK_ICON_EMOJI: ':rocket:'
        SLACK_COLOR: success
        SLACK_FOOTER: 'WPSyntex CI'

    - name: Send failure Slack notification
      uses: rtCamp/action-slack-notify@v2
      if: ${{ inputs.is-success == false }}
      env:
        SLACK_WEBHOOK: ${{ inputs.webhook }}
        SLACK_USERNAME: GitHub
        SLACK_ICON_EMOJI: ':boom:'
        SLACK_COLOR: failure
        SLACK_FOOTER: 'WPSyntex CI'
