name: Run Playwright e2e Tests

description: Installs WordPress, starts the server, builds dependencies and run Playwright tests. Currently runs on PHP 8.0 with WordPress latest release.

permissions:
  contents: read

runs:
  using: 'composite'

  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 22
    - run: npm install
      shell: bash
    - run: npm run build --if-present
      shell: bash

    - name: Install Playwright dependencies
        # Only Chromium for the moment.
      run: |
        npx playwright install chromium --with-deps
      shell: bash

    # Must install PHP deps before wp-env is running to prevent errors.
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        coverage: none
        php-version: '8.0'

    - name: Install PHP Dependencies
      uses: ramsey/composer-install@v3
      with:
        dependency-versions: 'highest'
        composer-options: '--no-dev'

    - name: Install WordPress and start the server
      run: |
        npm run wp-env start
      shell: bash
      env:
        WP_ENV_PHP_VERSION: '8.0'

    - name: Run Playwright tests
      run: |
        npm run test:e2e
      shell: bash

    - name: Upload Playwright report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 7
