name: Run Playwright e2e Tests

description: Installs WordPress, starts the server, builds dependencies and run Playwright tests. Currently runs on PHP 8.0 with WordPress latest release.

permissions:
  contents: read

runs:
  using: 'composite'

  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm ci
    - run: npm run build --if-present

    - name: Install Playwright dependencies
        # Only Chromium for the moment.
      run: |
        npx playwright install chromium --with-deps

    # Must install PHP deps before wp-env is running to prevent errors.
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        coverage: none
        php-version: '8.0'

    - name: Install PHP Dependencies
      uses: ramsey/composer-install@v2
      with:
        dependency-versions: 'highest'
        composer-options: '--no-dev'

    - name: Install WordPress and start the server
      run: |
        npm run wp-env start
      env:
        WP_ENV_PHP_VERSION: '8.0'

    - name: Run Playwright tests
      run: |
        npx playwright test --config tests/e2e/playwright.config.js
