name: Run PHPUnit Tests

description: Sets up PHP and its dependencies, installs WordPress test library along with plugins and themes then runs PHPUnit tests.

inputs:
  php-version:
    description: PHP version to use.
    required: true
    type: string
  wordpress-version:
    description: WordPress version to use. Accepts a numeric string of the version, "nightly", or "latest".
    required: true
    type: string
  allow-failure:
    description: Whether or not the job is allowed to fail. Defaults to false.
    required: false
    type: boolean
    default: false

permissions:
  contents: read

runs:
  using: 'composite'

  steps:
    - name: Set up PHP ${{ inputs.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        coverage: none
        php-version: ${{ inputs.php-version }}

    - name: Check version requirement
      id: version-compare
      uses: polylang/actions/version-compare@main
      with:
        head: ${{ inputs.wordpress-version }}
        base: "5.9"

    - name: Clean PHP dependencies
      run: |
        if [[ ${{ steps.version-compare.outputs.result }} == true ]]; then
          composer require --no-interaction --no-update --ignore-platform-reqs --dev "phpunit/phpunit ^7.5"
        fi
        composer remove --no-interaction --no-update --dev "phpstan/phpstan"
        composer remove --no-interaction --no-update --dev "wpsyntex/polylang-phpstan"
      shell: bash

    - name: Install PHP Dependencies
      uses: ramsey/composer-install@v3
      with:
        dependency-versions: 'highest'

    - name: Install SVN
      # SVN is required by sjinks/setup-wordpress-test-library.
      run: |
        sudo apt-get update
        sudo apt-get install -y subversion
      shell: bash

    - name: Has SVN?
      run: which svn || exit 1
      shell: bash

    - name: Set up WordPress ${{ inputs.wordpress-version }} and WordPress Test Library
      uses: sjinks/setup-wordpress-test-library@v2.1.3
      with:
        version: ${{ inputs.wordpress-version }}

    - name: Set up plugins and themes dependencies
      run: |
        if [[ -f ./tests/bin/install-plugins.sh ]]; then
          bash ./tests/bin/install-plugins.sh
        fi
      shell: bash

    - name: Run PHPUnit tests
      run: |
        composer test -- --verbose
      shell: bash
